name: Docker build on push

on:
  push:
    paths:
    - 'Dockerfile'
    tags:
    - ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the dev image
      run: docker build . --file Dockerfile --tag tuetenk0pp/sharelatex-full:dev
